import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-employee-benefits-premium-eligibility-reconciliation",
  "engine": "recovery",
  "title": "Employee Benefits Premium & Eligibility Reconciliation",
  "shortTitle": "Employee Benefits Premium and Eligibility Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through employee benefits premium & eligibility reconciliation",
  "industry": "Benefits Financial Operations",
  "uiPort": 4599,
  "apiPort": 5599,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Employee Benefits Premium & Eligibility Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedPremium",
    "expectedKey": "supportedPremium",
    "actualLabel": "Carrier Billed Premium",
    "expectedLabel": "Eligibility-Supported Premium",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Employee Benefits Premium & Eligibility Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("plan-and-rate-library","EBP01","Plan and rate library","Execute plan and rate library using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed plan and rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Plan and rate library Reference","text","EBP01-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("employee-dependent-census","EBP02","Employee dependent census","Execute employee dependent census using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed employee dependent census decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Employee dependent census Reference","text","EBP02-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("enrollment-ingestion","EBP03","Enrollment ingestion","Execute enrollment ingestion using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed enrollment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Enrollment ingestion Reference","text","EBP03-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("carrier-invoice-ingestion","EBP04","Carrier invoice ingestion","Execute carrier invoice ingestion using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed carrier invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Carrier invoice ingestion Reference","text","EBP04-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("retro-enrollment-validation","EBP05","Retro enrollment validation","Execute retro enrollment validation using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed retro enrollment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Retro enrollment validation Reference","text","EBP05-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("terminated-member-detection","EBP06","Terminated member detection","Execute terminated member detection using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed terminated member detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Terminated member detection Reference","text","EBP06-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("life-event-effective-dates","EBP07","Life-event effective dates","Execute life-event effective dates using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed life-event effective dates decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Life-event effective dates Reference","text","EBP07-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("cobra-reconciliation","EBP08","COBRA reconciliation","Execute cobra reconciliation using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed cobra reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","COBRA reconciliation Reference","text","EBP08-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("leave-of-absence-billing","EBP09","Leave-of-absence billing","Execute leave-of-absence billing using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed leave-of-absence billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Leave-of-absence billing Reference","text","EBP09-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("age-banded-premium-validation","EBP10","Age-banded premium validation","Execute age-banded premium validation using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed age-banded premium validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Age-banded premium validation Reference","text","EBP10-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("self-billed-premium-calculation","EBP11","Self-billed premium calculation","Execute self-billed premium calculation using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed self-billed premium calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Self-billed premium calculation Reference","text","EBP11-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("carrier-discrepancy-workflow","EBP12","Carrier discrepancy workflow","Execute carrier discrepancy workflow using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed carrier discrepancy workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Carrier discrepancy workflow Reference","text","EBP12-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("premium-credit-tracking","EBP13","Premium credit tracking","Execute premium credit tracking using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed premium credit tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Premium credit tracking Reference","text","EBP13-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("payroll-deduction-reconciliation","EBP14","Payroll deduction reconciliation","Execute payroll deduction reconciliation using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed payroll deduction reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Payroll deduction reconciliation Reference","text","EBP14-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]}),
feature("plan-and-carrier-analytics","EBP15","Plan and carrier analytics","Execute plan and carrier analytics using plan rates, employee and dependent censuses, enrollment elections, life events, carrier invoices, COBRA, leave records, payroll deductions, credits, and correspondence.","Produce a governed plan and carrier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Carrier Plan","text","Employer / Carrier Plan · Standard Case"],["caseReference","Plan and carrier analytics Reference","text","EBP15-2026-001"],["billedPremium","Carrier Billed Premium","currency",568000],["supportedPremium","Eligibility-Supported Premium","currency",488480],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedPremium",subjects:["Plan and rate library case","Employee dependent census case","Enrollment ingestion case","Carrier invoice ingestion case","Retro enrollment validation case"]})
]);
